version: '3'
services:
  psql_todo:
    image: postgres:13.0
    restart: unless-stopped
    container_name: psql_todo
    tty: true
    ports:
        - '127.0.0.1:65432:5432'
    environment:
        POSTGRES_PASSWORD: 'root'
        POSTGRES_USER: 'root'
        POSTGRES_DB: 'todo'
        PGDATA: /data/postgres
    volumes:
      - ./dbdata:/data/postgres
      - ./initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
    networks:
        dbtest-net:
         aliases:
         - psql_todo
#Docker Networks
networks:
  dbtest-net:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
